### ISSUE TITLE
Test the weather app and provide screenshots

### ISSUE THREAD

**Issue by xcyberpunkx0** [xcyberpunkx0/SkiWeather#2]

**Comment by mukul018** [comment]
Please assign this to me.

**Comment by aryankshl** [comment]
hey @xcyberpunkx0 can you please assign this to me?

**Comment by ravneet1805** [comment]
hey @xcyberpunkx0 please assign me this issue.

**Comment by MrDBC** [comment]
so , is this PR closed? 
becoz i can see a commit by @xcyberpunkx0

**Comment by xcyberpunkx0** [comment]
Yes its closed.
